### ISSUE TITLE
Size data?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#16]
Is there any morphometric data for the oysters in this experiment?

**Comment by sr320** [comment]
@grace-ac .. what do you think?

**Comment by grace-ac** [comment]
Here's link to Jake's notebook page titled "11 11 2014 NEW Size Distribution Graphs with STATS!" Link http://heareresearch.blogspot.com/2014/11/11-11-2014-new-size-distribution-graphs.html

This may not be what you're looking for. Unfortunately don't have a whole lot of time this morning before I go babysit! 

Otherwise, I can only think of this spreadsheet that Jake shared with me years back: https://docs.google.com/spreadsheets/d/1IuEoLpebLlMkaZd9DC6dYV45eoMNUJ30ZXy9aD_4sXs/edit#gid=4

**Comment by kubu4** [comment]
Thanks. Any chance you can make that Google Sheet publicly viewable? As it is now, it requires me to request access.

**Comment by kubu4** [comment]
Thanks @grace-ac ! Here's the publicly viewable link for that Google Sheet she mentioned above: https://docs.google.com/spreadsheets/d/1IuEoLpebLlMkaZd9DC6dYV45eoMNUJ30ZXy9aD_4sXs/edit?usp=sharing

**Comment by kubu4** [comment]
Jake's notebook entry (when the experiment was conducted) for [20150423](http://heareresearch.blogspot.com/2015/04/4-23-2015-heatmechanical-shock-24-hour.html) indicates:
> shells placed in labeled plastic bags so correspond to sample including oyster id

Would we know if we still have these and, if yes, know where we can find them?

**Comment by kubu4** [comment]
Adding this info for posterity.

The [OlyO_Master.tsv](https://github.com/RobertsLab/project-olympia.oyster-genomic/blob/master/data/OlyO_Master.tsv) does <em>not</em> have this information. It only has data for samples from 2013.

**Comment by kubu4** [comment]
Not providing size data in manuscript.
